permalink:           /:categories/:title
paginate_path:       /:num

# Setup
title:               Topor
tagline:             'We axe the questions'
description:         'Topor is what makes the impossible possible.'
url:                 http://topor.jdl.ro
baseurl:             ''
paginate:            3

# About/contact
author:
  name:              Topor
  url:               http://topor.jdl.ro
  email:             toporteam@gmail.com
github:
  username:          thetopor
  url:               https://github.com/thetopor
# Custom vars


# Build settings
encoding: "utf-8"
markdown: redcarpet
markdown_ext: "markdown,md"
redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "with_toc_data", "footnotes"]
gems: [jekyll-paginate]

exclude: [README.md, LICENSE, CNAME]
